[package]
name = "bevy_mod_localization"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
async-fs = "2.1.2"
crossbeam-channel = "0.5.13"
futures-lite = "2.3.0"
notify-debouncer-full = "0.3.1"
unic-langid = { version = "0.9.5", features = ["macros"] }

[dependencies.bevy]
path = "../bevy"
default-features = false
features = ["bevy_asset", "bevy_text"]

[dev-dependencies.bevy]
path = "../bevy"
