[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2021-0139", # ansi_term is unmaintained
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = ["MIT", "MIT-0", "Apache-2.0", "BSD-3-Clause", "ISC", "Zlib", "CC0-1.0"]
exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
default = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    { name = "ahash", version = "0.7" },
    { name = "bitflags", version = "1.3" },
    { name = "concurrent-queue", version = "1.2.2" },
    { name = "hashbrown", version = "0.12" },
    { name = "libloading", version = "0.7" },
    { name = "miniz_oxide", version = "0.6" },
    { name = "redox_syscall", version = "0.2" },
    { name = "regex-syntax", version = "0.6" },
    { name = "syn", version = "1.0" },
    { name = "windows-sys", version = "0.45" },
    { name = "windows-targets", version = "0.42" },
    { name = "windows_aarch64_gnullvm", version = "0.42" },
    { name = "windows_aarch64_msvc", version = "0.42" },
    { name = "windows_i686_gnu", version = "0.42" },
    { name = "windows_i686_msvc", version = "0.42" },
    { name = "windows_x86_64_gnu", version = "0.42" },
    { name = "windows_x86_64_gnullvm", version = "0.42" },
    { name = "windows_x86_64_msvc", version = "0.42" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
