name: Dependencies

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
      - ".github/workflows/dependencies.yml"
  push:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
      - ".github/workflows/dependencies.yml"
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Dependency checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-deny-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-deny
        run: cargo install cargo-deny
        continue-on-error: true
      - name: Check dependencies for duplicates, depedency issues and security advisories
        run: cargo deny check all
