name: Dependencies

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
      - ".github/workflows/dependencies.yml"
  push:
    paths:
      - "**/Cargo.toml"
      - "deny.toml"
      - ".github/workflows/dependencies.yml"
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    name: Dependency checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check dependencies for duplicates, depedency issues and security advisories
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: stable
